#!/bin/sh
powershell.exe -ExecutionPolicy RemoteSigned -File "$USERPROFILE/Dotfiles/Scripts/GitHooks/UpdatePowerToysBackup.ps1"
powershell.exe -ExecutionPolicy RemoteSigned -File "$USERPROFILE/Dotfiles/Scripts/GitHooks/SaveVsCodeExtensions.ps1"
git add "$USERPROFILE/Dotfiles/Config/PowerToys/latest_powertoys_backup.ptb"
git add "$USERPROFILE/Dotfiles/Config/VisualStudioCode/extensions"
